version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/install:
          working_directory: e2e
      - cypress/run:
          requires:
            - cypress/install
          working_directory: e2e
          pre-steps:
            - run: ls -A1
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
