version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

jobs:
  build-server:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          working_directory: server
          command: .ci/build.sh
  build-deploy-server:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          working_directory: server
          command: .ci/build.sh
      - run:
          name: Deploy
          working_directory: server
          command: .ci/deploy.sh
  build-ui:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ui
          command: .ci/build.sh
  build-deploy-ui:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ui
          command: .ci/build.sh
      - run:
          name: Deploy
          working_directory: ui
          command: .ci/deploy.sh
  deploy-docker-compose:
    machine: true
    steps:
      - checkout
      - run: echo ${SSH_HOST}
      - run: .ci/deploy.sh

workflows:
  build:
    jobs:
      - build-server:
          context: deploy
          filters:
            branches:
              ignore: master
      - build-ui:
          context: deploy
          filters:
            branches:
              ignore: master
  build-deploy:
    jobs:
      - deploy-docker-compose:
          context: deploy
          filters:
            branches:
              only: master
      - build-deploy-server:
          context: deploy
          filters:
            branches:
              only: master
      - build-deploy-ui:
          context: deploy
          filters:
            branches:
              only: master
      - cypress/run:
          requires:
            - deploy-docker-compose
            - build-deploy-server
            - build-deploy-ui
          filters:
            branches:
              only: master
          working_directory: e2e
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "e2e/package.json" }}'
          post-steps:
            - store_test_results:
                path: e2e/cypress/results
            - store_artifacts:
                path: e2e/cypress/screenshots
            - store_artifacts:
                path: e2e/cypress/videos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - cypress/run:
          filters:
            branches:
              only: master
          working_directory: e2e
          cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "e2e/package.json" }}'
          post-steps:
            - store_test_results:
                path: e2e/cypress/results
            - store_artifacts:
                path: e2e/cypress/screenshots
            - store_artifacts:
                path: e2e/cypress/videos
