version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: ssh -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "docker ps"
      - run: .ci/deploy-all.sh
      - run:
          working_directory: e2e
          command: .ci/build.sh
      - run:
          working_directory: e2e
          command: .ci/run.sh
      - run:
          working_directory: e2e
          command: .ci/copy-artifacts.sh
      - store_test_results:
          path: e2e/results
      - store_artifacts:
          path: e2e/results

workflows:
  build:
    jobs:
      - build:
          context: deploy
