version: 2.1

jobs:
  build-deploy-server:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build
          working_directory: server
          command: .ci/build.sh
      - run:
          name: Deploy
          working_directory: server
          command: .ci/deploy.sh
  build-deploy-ui:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build
          working_directory: ui
          command: .ci/build.sh
      - run:
          name: Deploy
          working_directory: ui
          command: .ci/deploy.sh
  deploy-docker-compose:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: .ci/deploy.sh
  verify-e2e:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          working_directory: e2e
          command: .ci/build.sh
      - run:
          working_directory: e2e
          command: .ci/run.sh
      - run:
          working_directory: e2e
          command: .ci/copy-artifacts.sh
      - store_test_results:
          path: e2e/results
      - store_artifacts:
          path: e2e/results

workflows:
  build-deploy:
    jobs:
      - deploy-docker-compose:
          - context: deploy
      - build-deploy-server:
          context: deploy
      - build-deploy-ui:
          context: deploy
      - verify-e2e:
          requires:
            - deploy-docker-compose
            - build-deploy-server
            - build-deploy-ui
