version: 2.1

jobs:
  build-server:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: (cd server && .ci/build.sh)
  build-ui:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: (cd ui && .ci/build.sh)
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: .ci/deploy.sh
  deploy-server:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: (cd server && .ci/deploy.sh)
  deploy-ui:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: (cd ui && .ci/deploy.sh)
  verify:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: (cd e2e && .ci/build.sh)
      - run: (cd e2e && .ci/run.sh)
      - run: (cd e2e && .ci/copy-artifacts.sh)
      - store_test_results:
          path: e2e/results
      - store_artifacts:
          path: e2e/results

workflows:
  build:
    jobs:
      - build-server:
          context: deploy
      - build-ui:
          context: deploy
      - deploy:
          requires:
            - build-ui
            - build-server
          context: deploy
      - deploy-server:
          requires:
            - build-ui
            - build-server
          context: deploy
      - deploy-ui:
          requires:
            - build-ui
            - build-server
          context: deploy
      - verify:
          requires:
            - deploy
            - deploy-ui
            - deploy-server
          context: deploy
