version: 2.1

jobs:
  build:
    machine: true
    steps:
      - run:
          name: Install git for checkout
          command: |
            apt-get update && apt-get --no-install-recommends -y install git
      - checkout
      - run: .ci/deploy-all.sh
      - run:
          working_directory: e2e
          command: .ci/build.sh
      - run:
          working_directory: e2e
          command: .ci/run.sh
      - run:
          working_directory: e2e
          command: .ci/copy-artifacts.sh
      - store_test_results:
          path: e2e/results
      - store_artifacts:
          path: e2e/results

workflows:
  build:
    jobs:
      - build:
          context: deploy
