version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/run:
          working_directory: e2e
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
