version: 2.1

jobs:
  build-deploy-verify:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Build Server
          working_directory: server
          command: .ci/build.sh
      - run:
          name: Build UI
          working_directory: ui
          command: .ci/build.sh
      - run: .ci/deploy.sh
      - run:
          name: Deploy Server
          working_directory: ui
          command: .ci/deploy.sh
      - run:
          name: Deploy UI
          working_directory: ui
          command: .ci/deploy.sh
      - run:
          name: Build E2E Test Image
          working_directory: e2e
          command: .ci/build.sh
      - run:
          name: Run E2E Tests
          working_directory: e2e
          command: .ci/run.sh
      - run:
          name: Copy out E2E test results
          working_directory: e2e
          command: .ci/copy-artifacts.sh
      - store_test_results:
          path: e2e/results
      - store_artifacts:
          path: e2e/results

workflows:
  build:
    jobs:
      - build-deploy-verify:
          context: deploy
