env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - plugin:testing-library/react
  - plugin:jest-dom/recommended
  - plugin:prettier/recommended
  - plugin:compat/recommended
  - plugin:jsx-a11y/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
  - jest
  - testing-library
  - jest-dom
settings:
  import/resolver:
    typescript: {}
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
      - .tsx
      - .jsx
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/*.test.*'
  no-restricted-exports: off
  react/jsx-props-no-spreading: off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  no-shadow: off
  '@typescript-eslint/no-shadow': off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  react/require-default-props: off
